"""Stable, opaque identifiers for missions, steps, and mission traces.

Ids are generated by the platform and are never derived from anything mutable or guessable
(ADR 0040 §1 fixes this rule for tenants; missions and steps follow it). Prefixes make an id
self-describing wherever it appears — a log line, an event, an audit record — so a reader
never has to guess what `mis_…` versus `stp_…` refers to (CLAUDE.md §21)."""

from __future__ import annotations

import uuid

MISSION_PREFIX = "mis"
STEP_PREFIX = "stp"
TRACE_PREFIX = "trc"


def _new(prefix: str) -> str:
    return f"{prefix}_{uuid.uuid4().hex}"


def new_mission_id() -> str:
    return _new(MISSION_PREFIX)


def new_step_id() -> str:
    return _new(STEP_PREFIX)


def new_trace_id() -> str:
    """A mission's trace id: the top of the trace tree its step traces nest under
    (ADR 0042 §4)."""
    return _new(TRACE_PREFIX)
