/**
 * Deterministic, no-egress fallback providers. Used when no external provider is configured
 * (`AI_PROVIDER=local` or missing `OPENAI_API_KEY`) and as a resilience backstop. Embeddings
 * are hashed bag-of-words vectors — good enough for lexical-ish similarity in dev/offline;
 * the local chat is extractive. Node-only.
 */

import { createHash } from "node:crypto";
import type { ChatMessage, ChatProvider, EmbeddingProvider } from "./provider";

const LOCAL_DIMENSION = 384;

function tokenize(text: string): string[] {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, " ")
    .split(/\s+/)
    .filter((token) => token.length > 1);
}

export class LocalEmbeddingProvider implements EmbeddingProvider {
  readonly id = `local:hash-${LOCAL_DIMENSION}`;
  readonly dimension = LOCAL_DIMENSION;

  async embed(texts: string[]): Promise<number[][]> {
    return texts.map((text) => this.embedOne(text));
  }

  private embedOne(text: string): number[] {
    const vector = new Array<number>(LOCAL_DIMENSION).fill(0);
    for (const token of tokenize(text)) {
      const hash = createHash("sha1").update(token).digest();
      const index = hash.readUInt32BE(0) % LOCAL_DIMENSION;
      const sign = (hash[4]! & 1) === 0 ? 1 : -1;
      vector[index]! += sign;
    }
    const norm = Math.sqrt(vector.reduce((sum, value) => sum + value * value, 0)) || 1;
    return vector.map((value) => value / norm);
  }
}

export class LocalChatProvider implements ChatProvider {
  readonly id = "local:extractive";

  async complete(messages: ChatMessage[], options: { json?: boolean } = {}): Promise<string> {
    const userContent = messages
      .filter((m) => m.role === "user")
      .map((m) => m.content)
      .join("\n");
    if (options.json) {
      // Minimal valid structure so the pipeline stays functional without an LLM. Matches
      // the assess_grc_document.v3 schema's required shape; every array defaults to empty.
      return JSON.stringify({
        executiveSummary: extractiveSummary(userContent),
        complianceOverview: "",
        findings: [],
        criticalRisks: [],
        frameworks: [],
        gaps: [],
        strengths: [],
        weaknesses: [],
        recommendations: [],
        businessImpact: "",
        overallPriority: { level: "medium", rationale: "" },
        references: [],
        nextActions: [],
        note: "Generated by the local fallback provider (no external LLM configured).",
      });
    }
    return extractiveSummary(userContent);
  }
}

function extractiveSummary(text: string): string {
  const sentences = text.split(/(?<=[.!?])\s+/).filter((s) => s.length > 30);
  return sentences.slice(0, 3).join(" ") || "No content available to summarize.";
}
