import type { Metadata } from "next";
import { FileBarChart, ShieldCheck, TriangleAlert } from "lucide-react";
import { Hero } from "@/components/marketing/Hero";
import { CTASection } from "@/components/marketing/CTASection";
import { Card } from "@/components/ui/Card";
import { Badge } from "@/components/ui/Badge";
import { ProgressBar } from "@/components/ui/ProgressBar";

export const metadata: Metadata = {
  title: "Example Reports · Sentinel GRC",
  description:
    "Sample executive, compliance, and risk reports generated by Sentinel GRC — audit-ready and exportable.",
};

const SAMPLE_REPORTS = [
  {
    icon: ShieldCheck,
    title: "Executive Summary",
    tone: "accent" as const,
    kpis: [
      { label: "Overall coverage", value: "78%" },
      { label: "Open gaps", value: "12" },
      { label: "Frameworks tracked", value: "4" },
    ],
    narrative:
      "Sample data. Coverage improved across ISO 27001 and NCA ECC this quarter, driven by newly linked evidence for access-control and logging requirements. Twelve control gaps remain open, concentrated in vendor risk management.",
  },
  {
    icon: FileBarChart,
    title: "Compliance Report",
    tone: "success" as const,
    kpis: [
      { label: "Controls covered", value: "142 / 182" },
      { label: "Evidence artifacts", value: "96" },
      { label: "Frameworks", value: "ISO 27001, NCA ECC" },
    ],
    narrative:
      "Sample data. Per-framework breakdown of covered vs. gap controls, with the evidence backing each covered control and a prioritized list of the highest-impact gaps to close next.",
  },
  {
    icon: TriangleAlert,
    title: "Risk Report",
    tone: "warning" as const,
    kpis: [
      { label: "Open risks", value: "9" },
      { label: "Average score", value: "11.4" },
      { label: "Critical", value: "2" },
    ],
    narrative:
      "Sample data. Inherent and residual scoring for every tracked risk, mitigation status, and ownership — ready to hand to leadership or an external auditor as-is.",
  },
];

export default function SampleReportsPage() {
  return (
    <>
      <Hero
        eyebrow="Example reports"
        title="Audit-ready reports, generated on demand"
        description="The same executive, compliance, and risk reports your workspace produces live — shown here with sample data so you can see the output before you sign in."
      />

      <section className="mx-auto max-w-[1000px] space-y-6 px-4 py-20 sm:px-6">
        {SAMPLE_REPORTS.map((report) => {
          const Icon = report.icon;
          return (
            <Card key={report.title} className="p-8">
              <div className="flex items-start justify-between gap-4">
                <div className="flex items-center gap-3">
                  <div className="flex h-10 w-10 items-center justify-center rounded-xl border border-hairline-strong bg-surface-2 shadow-soft">
                    <Icon className="h-[18px] w-[18px] text-accent" strokeWidth={1.75} />
                  </div>
                  <h3 className="text-base font-semibold tracking-tight text-foreground">
                    {report.title}
                  </h3>
                </div>
                <Badge tone="neutral">Sample</Badge>
              </div>

              <div className="mt-6 grid grid-cols-1 gap-4 sm:grid-cols-3">
                {report.kpis.map((kpi) => (
                  <div key={kpi.label} className="rounded-xl border border-hairline p-4">
                    <p className="text-2xs uppercase tracking-wider text-foreground-muted">
                      {kpi.label}
                    </p>
                    <p className="mt-1 text-xl font-semibold tracking-tight text-foreground">
                      {kpi.value}
                    </p>
                  </div>
                ))}
              </div>

              <ProgressBar value={78} tone={report.tone} className="mt-6" />

              <p className="mt-4 text-sm leading-relaxed text-foreground-secondary">
                {report.narrative}
              </p>
            </Card>
          );
        })}
      </section>

      <CTASection
        title="Generate this against your own evidence"
        description="Every report above is built live from your coverage, evidence, and risk data once you sign in."
      />
    </>
  );
}
