/**
 * Locale-keyed labels for the generated report "chrome" (titles, section headings, KPI
 * labels, table column headers) — everything in `Report` that isn't a direct copy of tenant
 * data (risk titles, policy names, framework short names stay as stored/canonical, per
 * CLAUDE.md — internationally recognized framework names/codes are never translated).
 * Node-only; consumed by `lib/reports/service.ts`.
 */

import type { AppLocale } from "@/i18n/routing";
import type { RiskCategory, RiskStatus, Severity } from "@/lib/risk/types";
import type { ReportKind } from "./types";

export interface ReportLabels {
  meta: Record<ReportKind, { title: string; subtitle: string }>;
  tenantPrefix: string;
  generatedByPrefix: string;
  kpis: {
    complianceCoverage: string;
    controlGaps: string;
    openRisks: string;
    criticalRisks: string;
    evidenceArtifacts: string;
    publishedPolicies: string;
    overallCoverage: string;
    controlsCovered: string;
    openGaps: string;
    policies: string;
    totalRisks: string;
    critical: string;
    high: string;
    accepted: string;
    averageScore: string;
  };
  sections: {
    frameworkCoverage: string;
    topRisks: string;
    controlGaps: string;
    policyRegister: string;
    severityDistribution: string;
    riskRegister: string;
  };
  tables: {
    frameworkCoverageTitle: string;
    highestScoringRisks: string;
    controlsWithoutEvidence: string;
    policyRegisterTitle: string;
    risksBySeverity: string;
    allRisks: string;
    noControlGaps: string;
  };
  columns: {
    framework: string;
    controls: string;
    covered: string;
    coverage: string;
    region: string;
    risk: string;
    category: string;
    score: string;
    severity: string;
    status: string;
    control: string;
    title: string;
    policy: string;
    owner: string;
    mappedControls: string;
    count: string;
    inherent: string;
    residual: string;
  };
  severity: Record<Severity, string>;
  riskStatus: Record<RiskStatus, string>;
  riskCategory: Record<RiskCategory, string>;
}

const EN: ReportLabels = {
  meta: {
    executive: {
      title: "Executive GRC Report",
      subtitle: "Governance, risk & compliance posture at a glance",
    },
    compliance: {
      title: "Compliance Report",
      subtitle: "Framework coverage and control assurance",
    },
    risk: { title: "Risk Report", subtitle: "Risk register, scoring, and treatment" },
  },
  tenantPrefix: "Tenant",
  generatedByPrefix: "Generated by",
  kpis: {
    complianceCoverage: "Compliance coverage",
    controlGaps: "Control gaps",
    openRisks: "Open risks",
    criticalRisks: "Critical risks",
    evidenceArtifacts: "Evidence artifacts",
    publishedPolicies: "Published policies",
    overallCoverage: "Overall coverage",
    controlsCovered: "Controls covered",
    openGaps: "Open gaps",
    policies: "Policies",
    totalRisks: "Total risks",
    critical: "Critical",
    high: "High",
    accepted: "Accepted",
    averageScore: "Average score",
  },
  sections: {
    frameworkCoverage: "Framework coverage",
    topRisks: "Top risks by inherent score",
    controlGaps: "Control gaps",
    policyRegister: "Policies",
    severityDistribution: "Severity distribution",
    riskRegister: "Risk register",
  },
  tables: {
    frameworkCoverageTitle: "Coverage by framework",
    highestScoringRisks: "Highest-scoring risks",
    controlsWithoutEvidence: "Controls without evidence",
    policyRegisterTitle: "Policy register",
    risksBySeverity: "Risks by severity",
    allRisks: "All risks",
    noControlGaps: "No control gaps — every catalogued control has linked evidence.",
  },
  columns: {
    framework: "Framework",
    controls: "Controls",
    covered: "Covered",
    coverage: "Coverage",
    region: "Region",
    risk: "Risk",
    category: "Category",
    score: "Score",
    severity: "Severity",
    status: "Status",
    control: "Control",
    title: "Title",
    policy: "Policy",
    owner: "Owner",
    mappedControls: "Mapped controls",
    count: "Count",
    inherent: "Inherent",
    residual: "Residual",
  },
  severity: { low: "Low", medium: "Medium", high: "High", critical: "Critical" },
  riskStatus: { open: "Open", mitigating: "Mitigating", accepted: "Accepted", closed: "Closed" },
  riskCategory: {
    cyber: "Cyber",
    compliance: "Compliance",
    privacy: "Privacy",
    operational: "Operational",
    third_party: "Third party",
    financial: "Financial",
  },
};

const AR: ReportLabels = {
  meta: {
    executive: {
      title: "التقرير التنفيذي للحوكمة والمخاطر والامتثال",
      subtitle: "نظرة شاملة على وضع الحوكمة والمخاطر والامتثال",
    },
    compliance: {
      title: "تقرير الامتثال",
      subtitle: "تغطية الأطر التنظيمية وضمان الضوابط",
    },
    risk: { title: "تقرير المخاطر", subtitle: "سجل المخاطر والتقييم والمعالجة" },
  },
  tenantPrefix: "الجهة",
  generatedByPrefix: "أُعد بواسطة",
  kpis: {
    complianceCoverage: "تغطية الامتثال",
    controlGaps: "فجوات الضوابط",
    openRisks: "المخاطر المفتوحة",
    criticalRisks: "المخاطر الحرجة",
    evidenceArtifacts: "الأدلة الموثقة",
    publishedPolicies: "السياسات المعتمدة",
    overallCoverage: "التغطية الإجمالية",
    controlsCovered: "الضوابط المغطاة",
    openGaps: "الفجوات المفتوحة",
    policies: "السياسات",
    totalRisks: "إجمالي المخاطر",
    critical: "حرجة",
    high: "عالية",
    accepted: "مقبولة",
    averageScore: "متوسط الدرجة",
  },
  sections: {
    frameworkCoverage: "تغطية الأطر التنظيمية",
    topRisks: "أعلى المخاطر حسب درجة الخطورة الكامنة",
    controlGaps: "فجوات الضوابط",
    policyRegister: "السياسات",
    severityDistribution: "توزيع درجات الخطورة",
    riskRegister: "سجل المخاطر",
  },
  tables: {
    frameworkCoverageTitle: "التغطية حسب الإطار",
    highestScoringRisks: "أعلى المخاطر درجة",
    controlsWithoutEvidence: "الضوابط بدون أدلة",
    policyRegisterTitle: "سجل السياسات",
    risksBySeverity: "المخاطر حسب درجة الخطورة",
    allRisks: "جميع المخاطر",
    noControlGaps: "لا توجد فجوات في الضوابط — كل ضابط مُصنّف مرتبط بدليل.",
  },
  columns: {
    framework: "الإطار",
    controls: "الضوابط",
    covered: "المغطاة",
    coverage: "نسبة التغطية",
    region: "المنطقة",
    risk: "الخطر",
    category: "الفئة",
    score: "الدرجة",
    severity: "درجة الخطورة",
    status: "الحالة",
    control: "الضابط",
    title: "العنوان",
    policy: "السياسة",
    owner: "المالك",
    mappedControls: "الضوابط المرتبطة",
    count: "العدد",
    inherent: "الكامنة",
    residual: "المتبقية",
  },
  severity: { low: "منخفضة", medium: "متوسطة", high: "عالية", critical: "حرجة" },
  riskStatus: { open: "مفتوح", mitigating: "قيد التخفيف", accepted: "مقبول", closed: "مغلق" },
  riskCategory: {
    cyber: "سيبراني",
    compliance: "امتثال",
    privacy: "خصوصية",
    operational: "تشغيلي",
    third_party: "طرف ثالث",
    financial: "مالي",
  },
};

export function getReportLabels(locale: AppLocale): ReportLabels {
  return locale === "ar" ? AR : EN;
}
