"""initial schema

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-06-26 18:30:09.806553
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from grc_persistence.db.types import JSONColumn

# revision identifiers, used by Alembic.
revision: str = "0001_initial_schema"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_descriptors",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("agent_type", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("allowed_tool_ids", JSONColumn, nullable=False),
        sa.Column("data_scopes", JSONColumn, nullable=False),
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_descriptors")),
    )
    op.create_index(op.f("ix_agent_descriptors_name"), "agent_descriptors", ["name"], unique=False)
    op.create_table(
        "framework_mapping_sets",
        sa.Column("source_framework_id", sa.String(length=255), nullable=False),
        sa.Column("target_framework_id", sa.String(length=255), nullable=False),
        sa.Column("correspondences", JSONColumn, nullable=False),
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_framework_mapping_sets")),
    )
    op.create_index(
        op.f("ix_framework_mapping_sets_source_framework_id"),
        "framework_mapping_sets",
        ["source_framework_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_framework_mapping_sets_target_framework_id"),
        "framework_mapping_sets",
        ["target_framework_id"],
        unique=False,
    )
    op.create_table(
        "frameworks",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("version_label", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("region", sa.String(length=16), nullable=True),
        sa.Column("languages", JSONColumn, nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("controls", JSONColumn, nullable=False),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", "version_label", name=op.f("pk_frameworks")),
    )
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("region", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
    )
    op.create_table(
        "outbox_messages",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=255), nullable=False),
        sa.Column("aggregate_type", sa.String(length=255), nullable=False),
        sa.Column("aggregate_id", sa.String(length=255), nullable=False),
        sa.Column("organization_id", sa.String(length=255), nullable=True),
        sa.Column("payload", JSONColumn, nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("trace_id", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_messages")),
    )
    op.create_index(
        op.f("ix_outbox_messages_aggregate_id"), "outbox_messages", ["aggregate_id"], unique=False
    )
    op.create_index(
        op.f("ix_outbox_messages_event_type"), "outbox_messages", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_outbox_messages_organization_id"),
        "outbox_messages",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_outbox_messages_published_at"), "outbox_messages", ["published_at"], unique=False
    )
    op.create_table(
        "plugin_descriptors",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("version_label", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("provided_tool_ids", JSONColumn, nullable=False),
        sa.Column("provided_agent_ids", JSONColumn, nullable=False),
        sa.Column("required_permissions", JSONColumn, nullable=False),
        sa.Column("compatibility", JSONColumn, nullable=True),
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plugin_descriptors")),
    )
    op.create_index(
        op.f("ix_plugin_descriptors_name"), "plugin_descriptors", ["name"], unique=False
    )
    op.create_table(
        "tool_descriptors",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("version_label", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("side_effect", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("requires_approval", sa.Boolean(), nullable=False),
        sa.Column("required_permissions", JSONColumn, nullable=False),
        sa.Column("input_schema", JSONColumn, nullable=True),
        sa.Column("output_schema", JSONColumn, nullable=True),
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tool_descriptors")),
    )
    op.create_index(op.f("ix_tool_descriptors_name"), "tool_descriptors", ["name"], unique=False)
    op.create_table(
        "assessments",
        sa.Column("organization_id", sa.String(length=255), nullable=False),
        sa.Column("workspace_id", sa.String(length=255), nullable=False),
        sa.Column("framework_id", sa.String(length=255), nullable=False),
        sa.Column("framework_version_label", sa.String(length=64), nullable=False),
        sa.Column("assessment_type", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("results", JSONColumn, nullable=False),
        sa.Column("summary", JSONColumn, nullable=True),
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_assessments_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assessments")),
    )
    op.create_index(
        op.f("ix_assessments_organization_id"), "assessments", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_assessments_workspace_id"), "assessments", ["workspace_id"], unique=False
    )
    op.create_table(
        "audit_records",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("organization_id", sa.String(length=255), nullable=False),
        sa.Column("actor", JSONColumn, nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("action", sa.String(length=255), nullable=False),
        sa.Column("object_type", sa.String(length=255), nullable=False),
        sa.Column("object_id", sa.String(length=255), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("trace", JSONColumn, nullable=True),
        sa.Column("ai_call", JSONColumn, nullable=True),
        sa.Column("payload_hash", sa.String(length=255), nullable=True),
        sa.Column("source_ids", JSONColumn, nullable=False),
        sa.Column("outcome", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_audit_records_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_records")),
    )
    op.create_index(
        op.f("ix_audit_records_object_id"), "audit_records", ["object_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_records_object_type"), "audit_records", ["object_type"], unique=False
    )
    op.create_index(
        op.f("ix_audit_records_occurred_at"), "audit_records", ["occurred_at"], unique=False
    )
    op.create_index(
        op.f("ix_audit_records_organization_id"), "audit_records", ["organization_id"], unique=False
    )
    op.create_table(
        "controls",
        sa.Column("organization_id", sa.String(length=255), nullable=False),
        sa.Column("workspace_id", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("owner_id", sa.String(length=255), nullable=True),
        sa.Column("implementation_status", sa.String(length=32), nullable=False),
        sa.Column("framework_controls", JSONColumn, nullable=False),
        sa.Column("evidence_ids", JSONColumn, nullable=False),
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_controls_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_controls")),
    )
    op.create_index(
        op.f("ix_controls_organization_id"), "controls", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_controls_workspace_id"), "controls", ["workspace_id"], unique=False)
    op.create_table(
        "evidence",
        sa.Column("organization_id", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("evidence_type", sa.String(length=32), nullable=False),
        sa.Column("knowledge_source_id", sa.String(length=255), nullable=True),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("validity_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("validity_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("linked_control_ids", JSONColumn, nullable=False),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_evidence_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence")),
    )
    op.create_index(
        op.f("ix_evidence_organization_id"), "evidence", ["organization_id"], unique=False
    )
    op.create_table(
        "knowledge_sources",
        sa.Column("organization_id", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("locator_uri", sa.Text(), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=True),
        sa.Column("classification", sa.String(length=32), nullable=False),
        sa.Column("ingestion_status", sa.String(length=32), nullable=False),
        sa.Column("checksum_algorithm", sa.String(length=64), nullable=True),
        sa.Column("checksum_value", sa.String(length=255), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_knowledge_sources_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_sources")),
    )
    op.create_index(
        op.f("ix_knowledge_sources_organization_id"),
        "knowledge_sources",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "missions",
        sa.Column("organization_id", sa.String(length=255), nullable=False),
        sa.Column("workspace_id", sa.String(length=255), nullable=False),
        sa.Column("goal", sa.Text(), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column("owner_id", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_missions_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_missions")),
    )
    op.create_index(
        op.f("ix_missions_organization_id"), "missions", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_missions_workspace_id"), "missions", ["workspace_id"], unique=False)
    op.create_table(
        "policies",
        sa.Column("organization_id", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("owner_id", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("policy_version", sa.Integer(), nullable=False),
        sa.Column("approved_by", sa.String(length=255), nullable=True),
        sa.Column("linked_control_ids", JSONColumn, nullable=False),
        sa.Column("framework_controls", JSONColumn, nullable=False),
        sa.Column("citations", JSONColumn, nullable=False),
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_policies_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policies")),
    )
    op.create_index(
        op.f("ix_policies_organization_id"), "policies", ["organization_id"], unique=False
    )
    op.create_table(
        "reports",
        sa.Column("organization_id", sa.String(length=255), nullable=False),
        sa.Column("report_type", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("source_mission_id", sa.String(length=255), nullable=True),
        sa.Column("source_assessment_id", sa.String(length=255), nullable=True),
        sa.Column("sections", JSONColumn, nullable=False),
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_reports_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
    )
    op.create_index(
        op.f("ix_reports_organization_id"), "reports", ["organization_id"], unique=False
    )
    op.create_table(
        "risks",
        sa.Column("organization_id", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=255), nullable=True),
        sa.Column("owner_id", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("score", JSONColumn, nullable=True),
        sa.Column("treatment", sa.String(length=32), nullable=True),
        sa.Column("accepted_by", sa.String(length=255), nullable=True),
        sa.Column("acceptance_rationale", sa.Text(), nullable=True),
        sa.Column("mitigating_control_ids", JSONColumn, nullable=False),
        sa.Column("evidence_ids", JSONColumn, nullable=False),
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_risks_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risks")),
    )
    op.create_index(op.f("ix_risks_organization_id"), "risks", ["organization_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("organization_id", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("roles", JSONColumn, nullable=False),
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_users_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_organization_id"), "users", ["organization_id"], unique=False)
    op.create_table(
        "workspaces",
        sa.Column("organization_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("owner_id", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("member_ids", JSONColumn, nullable=False),
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_workspaces_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workspaces")),
    )
    op.create_index(
        op.f("ix_workspaces_organization_id"), "workspaces", ["organization_id"], unique=False
    )
    op.create_table(
        "mission_approval_gates",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("mission_id", sa.String(length=255), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("step_id", sa.String(length=255), nullable=False),
        sa.Column("proposed_action", JSONColumn, nullable=False),
        sa.Column("decision", sa.String(length=32), nullable=False),
        sa.Column("decided_by", sa.String(length=255), nullable=True),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["mission_id"],
            ["missions.id"],
            name=op.f("fk_mission_approval_gates_mission_id_missions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mission_approval_gates")),
    )
    op.create_index(
        op.f("ix_mission_approval_gates_mission_id"),
        "mission_approval_gates",
        ["mission_id"],
        unique=False,
    )
    op.create_table(
        "mission_steps",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("mission_id", sa.String(length=255), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("side_effect", sa.String(length=32), nullable=False),
        sa.Column("agent_id", sa.String(length=255), nullable=True),
        sa.Column("tool_ids", JSONColumn, nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("output_ref", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["mission_id"], ["missions.id"], name=op.f("fk_mission_steps_mission_id_missions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mission_steps")),
    )
    op.create_index(
        op.f("ix_mission_steps_mission_id"), "mission_steps", ["mission_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_mission_steps_mission_id"), table_name="mission_steps")
    op.drop_table("mission_steps")
    op.drop_index(op.f("ix_mission_approval_gates_mission_id"), table_name="mission_approval_gates")
    op.drop_table("mission_approval_gates")
    op.drop_index(op.f("ix_workspaces_organization_id"), table_name="workspaces")
    op.drop_table("workspaces")
    op.drop_index(op.f("ix_users_organization_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_risks_organization_id"), table_name="risks")
    op.drop_table("risks")
    op.drop_index(op.f("ix_reports_organization_id"), table_name="reports")
    op.drop_table("reports")
    op.drop_index(op.f("ix_policies_organization_id"), table_name="policies")
    op.drop_table("policies")
    op.drop_index(op.f("ix_missions_workspace_id"), table_name="missions")
    op.drop_index(op.f("ix_missions_organization_id"), table_name="missions")
    op.drop_table("missions")
    op.drop_index(op.f("ix_knowledge_sources_organization_id"), table_name="knowledge_sources")
    op.drop_table("knowledge_sources")
    op.drop_index(op.f("ix_evidence_organization_id"), table_name="evidence")
    op.drop_table("evidence")
    op.drop_index(op.f("ix_controls_workspace_id"), table_name="controls")
    op.drop_index(op.f("ix_controls_organization_id"), table_name="controls")
    op.drop_table("controls")
    op.drop_index(op.f("ix_audit_records_organization_id"), table_name="audit_records")
    op.drop_index(op.f("ix_audit_records_occurred_at"), table_name="audit_records")
    op.drop_index(op.f("ix_audit_records_object_type"), table_name="audit_records")
    op.drop_index(op.f("ix_audit_records_object_id"), table_name="audit_records")
    op.drop_table("audit_records")
    op.drop_index(op.f("ix_assessments_workspace_id"), table_name="assessments")
    op.drop_index(op.f("ix_assessments_organization_id"), table_name="assessments")
    op.drop_table("assessments")
    op.drop_index(op.f("ix_tool_descriptors_name"), table_name="tool_descriptors")
    op.drop_table("tool_descriptors")
    op.drop_index(op.f("ix_plugin_descriptors_name"), table_name="plugin_descriptors")
    op.drop_table("plugin_descriptors")
    op.drop_index(op.f("ix_outbox_messages_published_at"), table_name="outbox_messages")
    op.drop_index(op.f("ix_outbox_messages_organization_id"), table_name="outbox_messages")
    op.drop_index(op.f("ix_outbox_messages_event_type"), table_name="outbox_messages")
    op.drop_index(op.f("ix_outbox_messages_aggregate_id"), table_name="outbox_messages")
    op.drop_table("outbox_messages")
    op.drop_table("organizations")
    op.drop_table("frameworks")
    op.drop_index(
        op.f("ix_framework_mapping_sets_target_framework_id"), table_name="framework_mapping_sets"
    )
    op.drop_index(
        op.f("ix_framework_mapping_sets_source_framework_id"), table_name="framework_mapping_sets"
    )
    op.drop_table("framework_mapping_sets")
    op.drop_index(op.f("ix_agent_descriptors_name"), table_name="agent_descriptors")
    op.drop_table("agent_descriptors")
    # ### end Alembic commands ###
