import type { Metadata } from "next";
import { getTranslations } from "next-intl/server";
import { FileBarChart, ShieldCheck, TriangleAlert } from "lucide-react";
import { Hero } from "@/components/marketing/Hero";
import { CTASection } from "@/components/marketing/CTASection";
import { Card } from "@/components/ui/Card";
import { Badge } from "@/components/ui/Badge";
import { ProgressBar } from "@/components/ui/ProgressBar";

export const metadata: Metadata = {
  title: "Reports · Rasheed",
  description:
    "Sample executive, compliance, and risk reports generated by Rasheed to support governance and compliance decisions.",
};

const REPORT_ITEMS = [
  {
    icon: ShieldCheck,
    key: "executive",
    tone: "accent" as const,
    kpiValues: ["78%", "12", "4"],
  },
  {
    icon: FileBarChart,
    key: "compliance",
    tone: "success" as const,
    kpiValues: ["142 / 182", "96", "ISO 27001, NCA ECC"],
  },
  {
    icon: TriangleAlert,
    key: "risk",
    tone: "warning" as const,
    kpiValues: ["9", "11.4", "2"],
  },
] as const;

export default async function SampleReportsPage() {
  const t = await getTranslations("sampleReportsPage");

  const reports = REPORT_ITEMS.map((item) => ({
    icon: item.icon,
    tone: item.tone,
    title: t(`reports.${item.key}.title`),
    narrative: t(`reports.${item.key}.narrative`),
    kpis: (["kpi1", "kpi2", "kpi3"] as const).map((kpiKey, i) => ({
      label: t(`reports.${item.key}.${kpiKey}`),
      value: item.kpiValues[i],
    })),
  }));

  return (
    <>
      <Hero
        eyebrow={t("hero.eyebrow")}
        title={t("hero.title")}
        description={t("hero.description")}
      />

      <section className="mx-auto max-w-[1000px] space-y-6 px-4 py-20 sm:px-6">
        {reports.map((report) => {
          const Icon = report.icon;
          return (
            <Card key={report.title} className="p-8">
              <div className="flex items-start justify-between gap-4">
                <div className="flex items-center gap-3">
                  <div className="flex h-10 w-10 items-center justify-center rounded-xl border border-hairline-strong bg-surface-2 shadow-soft">
                    <Icon className="h-[18px] w-[18px] text-accent" strokeWidth={1.75} />
                  </div>
                  <h3 className="text-base font-semibold tracking-tight text-foreground">
                    {report.title}
                  </h3>
                </div>
                <Badge tone="neutral">{t("sampleBadge")}</Badge>
              </div>

              <div className="mt-6 grid grid-cols-1 gap-4 sm:grid-cols-3">
                {report.kpis.map((kpi) => (
                  <div key={kpi.label} className="rounded-xl border border-hairline p-4">
                    <p className="text-2xs uppercase tracking-wider text-foreground-muted">
                      {kpi.label}
                    </p>
                    <p className="mt-1 text-xl font-semibold tracking-tight text-foreground">
                      {kpi.value}
                    </p>
                  </div>
                ))}
              </div>

              <ProgressBar value={78} tone={report.tone} className="mt-6" />

              <p className="mt-4 text-sm leading-relaxed text-foreground-secondary">
                {report.narrative}
              </p>
            </Card>
          );
        })}
      </section>

      <CTASection
        title={t("cta.title")}
        description={t("cta.description")}
        ctaLabel={t("cta.button")}
      />
    </>
  );
}
